# Generated by Django 5.2.3 on 2025-07-03 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100, unique=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCarbonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_solar', models.BooleanField(default=False)),
                ('pct_solar', models.FloatField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carbon.farmercarbondata')),
            ],
        ),
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_types', models.CharField(max_length=200)),
                ('intercropping', models.BooleanField(default=False)),
                ('pct_land_used', models.FloatField()),
                ('pesticide_type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=20)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carbon.farmercarbondata')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical'), ('mixed', 'Mixed')], max_length=20)),
                ('qty_kg', models.FloatField()),
                ('freq_per_season', models.IntegerField()),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carbon.farmercarbondata')),
            ],
        ),
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_trees', models.PositiveIntegerField()),
                ('avg_height_m', models.FloatField()),
                ('avg_age_years', models.FloatField()),
                ('pct_indigenous', models.FloatField()),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carbon.farmercarbondata')),
            ],
        ),
        migrations.CreateModel(
            name='WasteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burns_waste', models.BooleanField(default=False)),
                ('uses_compost', models.BooleanField(default=False)),
                ('waste_separation', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carbon.farmercarbondata')),
            ],
        ),
    ]
