# Generated by Django 5.2.3 on 2025-06-29 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produce_images/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
