# Generated by Django 5.2.3 on 2025-07-02 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_produce_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_organic_fertilizer', models.BooleanField(default=False)),
                ('uses_solar_energy', models.BooleanField(default=False)),
                ('plants_trees', models.BooleanField(default=False)),
                ('burns_waste', models.BooleanField(default=False)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
