# Generated by Django 5.2.3 on 2025-07-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_carbonactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarbonActivity',
        ),
    ]
