# Generated by Django 5.2.3 on 2025-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_super_admin_user_operator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('field_operator', 'Field Operator')], max_length=15),
        ),
    ]
