# Generated by Django 5.2.3 on 2025-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='operator_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
