# Generated by Django 5.2.3 on 2025-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_tv', '0002_remove_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('news', 'News'), ('story', 'Success Story'), ('experiment', 'Experiment')], default='tutorial', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.CharField(blank=True, choices=[('dry', 'Dry Season'), ('wet', 'Wet Season'), ('harvest', 'Harvest')], max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
