# Generated by Django 5.2.3 on 2025-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_tv', '0005_tvview_tvrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
