# Generated by Django 5.2.3 on 2025-07-14 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_tv', '0006_alter_agrostringstvschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrostringstvschedule',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Indicates if the stream is currently live.'),
        ),
        migrations.AddField(
            model_name='agrostringstvschedule',
            name='stream_key',
            field=models.CharField(blank=True, help_text='The unique key for the broadcaster to use.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agrostringstvschedule',
            name='stream_type',
            field=models.CharField(choices=[('live', 'Live'), ('pre_recorded', 'Pre-Recorded')], default='pre_recorded', max_length=20),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='The time the live stream is scheduled to end.', null=True),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Swahili')], default='en', max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time the live stream is scheduled to start.'),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for pre-recorded content.', null=True, upload_to='tv_videos/'),
        ),
        migrations.AlterField(
            model_name='agrostringstvschedule',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link for pre-recorded content.', null=True),
        ),
    ]
